### ISSUE TITLE
nault in some instances shows recieve of send to self with twice the amount

### ISSUE THREAD

**Issue by My1** [Nault/Nault#171]
Edge case I know, but wanted to drop it just in case

![image](https://user-images.githubusercontent.com/6696524/90732758-dbace100-e2cb-11ea-9422-ef7b97d45bf8.png)

although for some weird reason out of 2 desktop and 2 web instances (both computers run windows 8.1 and Brave) only 1 web instance has this issue.

**Comment by Joohansson** [comment]
Thanks, will try and replicate this. I have an idea what the cause might be.

**Comment by Joohansson** [comment]
@My1 Can you please test in the web wallet if you can replicate this now. I'm fairly certain it's solved with the mentioned commit above. It was a race condition if the balance was reloading at the same time as another reload happened due to the new incoming being detected by the websocket.

**Comment by My1** [comment]
Need to try tomorrow at work at home the web wallet worked. But that was a weird race condition like depending on where it ran it triggered either always or never.

**Comment by Joohansson** [comment]
Thanks, yeah I think it depends on how fast the websocket is and that is depending on the backend node you are connected to.

**Comment by My1** [comment]
that may explain stuff. the internet at work is a lot better so things happening quickly in succession wouldnt be something I would be surprised with.

**Comment by My1** [comment]
sadly I can still get this. as you can see from the date/time this is from right now, and I ctrl+F5'd a few times too...

https://nault.cc/transaction/617C7DF7F6BBB01A51D03EAB81F9B1C65B941AC4BE40655EC41B3392EBF92013
that is the recieve block.

altho a refresh sets the recieve balance correctly, it just happens when I do that with nault still open

![image](https://user-images.githubusercontent.com/6696524/90868848-aff72d00-e397-11ea-83ce-c066c1913c1a.png)

**Comment by Joohansson** [comment]
Damn, I wish I could replicate this somehow. It would be so much easier to find the issue.
What OS and Browser do you use?

**Comment by My1** [comment]
OS is windows 8.1 and Browser is brave Version 1.12.114 Chromium: 84.0.4147.135 (Official Build) (64-bit)
but as said even I cant replicate that on my home PC which has the same basic setup

**Comment by Joohansson** [comment]
This issue seems to happen very rarely, or at all. If anyone sees it again, please let us know.
